### ISSUE TITLE
The nav bar doesn't move with the page as you scroll

### ISSUE THREAD

**Issue by prosaicpudding** [LWVPullman/LeagueWebsite#4]
(I thought maybe using issues would help us keep organized. )

**Comment by prosaicpudding** [comment]
Partially complete. Need to add header top margin to prevent the bar covering it up, and then making the background white in the masthead. Will finish at a later date. I'm sleepy

**Comment by LWVPullman** [comment]
It does not seem to look like this version we were trying to use: https://lenpaul.github.io/Millennial/

We will have to decide if that matters. Because the benefit of the other was the addition of the social media links.
