### ISSUE TITLE
No dropdowns on the nav bar

### ISSUE THREAD

**Issue by prosaicpudding** [LWVPullman/LeagueWebsite#8]

**Comment by LWVPullman** [comment]
Research so far:
    * There might be help from this template https://lenpaul.github.io/Millennial/, but it's incredibly simplistic in comparison to our current template
    * This poster got a version working but it's rittled with bugs https://github.com/mmistakes/minimal-mistakes/issues/1801
    * This is how 'collections' works in Jekyll. Which is likely the best way to create heirarchies https://jekyllrb.com/docs/collections/
    * This is how collections in MM works https://mmistakes.github.io/minimal-mistakes/docs/collections/

**Comment by prosaicpudding** [comment]
This isn't like, a good solution. But I did get a version working based on what that poster did. Seems to work.

**Comment by prosaicpudding** [comment]
Good enough.
